import PDFDocument from 'pdfkit';
import { IRecommendationDocument } from '../models/Recommendation.js';
import { IGemstoneDocument } from '../models/Gemstone.js';

export function generateRecommendationPDF(
  recommendation: IRecommendationDocument,
  gemstone: IGemstoneDocument,
  userName: string
): PDFKit.PDFDocument {
  const doc = new PDFDocument({ margin: 50 });

  // Header
  doc.fontSize(22).fillColor('#7c3aed').text('Gemstone Recommendation Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#666').text(`Generated on ${new Date().toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(1.5);

  // User info
  doc.fontSize(14).fillColor('#000').text('Personal Details', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(11).text(`Name: ${userName}`);
  doc.text(`Date of Birth: ${new Date(recommendation.birthDetails.dateOfBirth).toLocaleDateString()}`);
  doc.text(`Time of Birth: ${recommendation.birthDetails.timeOfBirth}`);
  doc.text(`Place of Birth: ${recommendation.birthDetails.placeOfBirth}`);
  doc.text(`Gender: ${recommendation.birthDetails.gender}`);
  doc.text(`Zodiac Sign: ${recommendation.zodiacSign}`);
  doc.moveDown(1);

  // Recommendation
  doc.fontSize(14).text('Recommended Gemstone', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(16).fillColor('#7c3aed').text(gemstone.name);
  doc.fillColor('#000').fontSize(11);
  doc.text(`Planet Association: ${gemstone.planet}`);
  doc.text(`Confidence Score: ${recommendation.confidenceScore}%`);
  doc.moveDown(0.5);
  doc.text(recommendation.reportSummary);
  doc.moveDown(1);

  // Benefits
  doc.fontSize(14).text('Benefits', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(11);
  gemstone.benefits.forEach((benefit) => {
    doc.text(`• ${benefit}`);
  });
  doc.moveDown(1);

  // Wearing instructions
  doc.fontSize(14).text('Wearing Instructions', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(11);
  doc.text(`Method: ${gemstone.wearingMethod}`);
  doc.text(`Recommended Metal: ${gemstone.recommendedMetal}`);
  doc.text(`Recommended Finger: ${gemstone.recommendedFinger}`);
  doc.text(`Recommended Day: ${gemstone.recommendedDay}`);
  doc.moveDown(2);

  // Footer
  doc.fontSize(9).fillColor('#999').text(
    'This report is generated by Gemstone Recommendation App for informational purposes. Consult a qualified astrologer before wearing gemstones.',
    { align: 'center' }
  );

  doc.end();
  return doc;
}
