import { GemstoneData, ZodiacSign } from '../types/index.js';

/** Default gemstone catalog used for seeding and fallback recommendations */
export const DEFAULT_GEMSTONES: GemstoneData[] = [
  {
    name: 'Ruby',
    planet: 'Sun',
    benefits: [
      'Enhances leadership and confidence',
      'Improves vitality and energy',
      'Strengthens willpower and courage',
      'Supports career growth and recognition',
    ],
    wearingMethod: 'Set in gold ring on the ring finger of the right hand. Purify with Ganga jal before wearing.',
    recommendedMetal: 'Gold',
    recommendedFinger: 'Ring finger (right hand)',
    recommendedDay: 'Sunday',
    zodiacSigns: ['Aries', 'Leo'],
  },
  {
    name: 'Emerald',
    planet: 'Mercury',
    benefits: [
      'Improves communication and intellect',
      'Enhances business acumen',
      'Supports mental clarity and focus',
      'Aids in creative expression',
    ],
    wearingMethod: 'Set in gold or silver on the little finger. Chant Mercury mantra before first wear.',
    recommendedMetal: 'Gold or Silver',
    recommendedFinger: 'Little finger (right hand)',
    recommendedDay: 'Wednesday',
    zodiacSigns: ['Taurus', 'Gemini', 'Virgo'],
  },
  {
    name: 'Pearl',
    planet: 'Moon',
    benefits: [
      'Promotes emotional balance and calmness',
      'Enhances intuition and nurturing qualities',
      'Supports mental peace and stability',
      'Improves relationships and compassion',
    ],
    wearingMethod: 'Set in silver on the little finger. Wear during waxing moon phase for best results.',
    recommendedMetal: 'Silver',
    recommendedFinger: 'Little finger (right hand)',
    recommendedDay: 'Monday',
    zodiacSigns: ['Cancer'],
  },
  {
    name: 'Diamond',
    planet: 'Venus',
    benefits: [
      'Attracts luxury and artistic talents',
      'Enhances beauty and charm',
      'Strengthens marital harmony',
      'Supports financial prosperity',
    ],
    wearingMethod: 'Set in platinum or white gold on the middle finger. Avoid wearing with incompatible stones.',
    recommendedMetal: 'Platinum or White Gold',
    recommendedFinger: 'Middle finger (right hand)',
    recommendedDay: 'Friday',
    zodiacSigns: ['Libra'],
  },
  {
    name: 'Coral',
    planet: 'Mars',
    benefits: [
      'Boosts courage and determination',
      'Improves physical strength and stamina',
      'Helps overcome obstacles and enemies',
      'Supports land and property matters',
    ],
    wearingMethod: 'Set in copper or gold on the ring finger. Wear after Mars hora on Tuesday.',
    recommendedMetal: 'Copper or Gold',
    recommendedFinger: 'Ring finger (right hand)',
    recommendedDay: 'Tuesday',
    zodiacSigns: ['Scorpio'],
  },
  {
    name: 'Yellow Sapphire',
    planet: 'Jupiter',
    benefits: [
      'Brings wisdom and spiritual growth',
      'Enhances fortune and prosperity',
      'Supports education and higher learning',
      'Promotes good health and longevity',
    ],
    wearingMethod: 'Set in gold on the index finger. Perform Jupiter puja before wearing.',
    recommendedMetal: 'Gold',
    recommendedFinger: 'Index finger (right hand)',
    recommendedDay: 'Thursday',
    zodiacSigns: ['Sagittarius', 'Pisces'],
  },
  {
    name: 'Blue Sapphire',
    planet: 'Saturn',
    benefits: [
      'Provides discipline and focus',
      'Protects from negative influences',
      'Supports career stability and longevity',
      'Enhances karmic balance',
    ],
    wearingMethod: 'Trial period of 3-7 days recommended. Set in silver or gold on middle finger.',
    recommendedMetal: 'Silver or Gold',
    recommendedFinger: 'Middle finger (right hand)',
    recommendedDay: 'Saturday',
    zodiacSigns: ['Capricorn'],
  },
  {
    name: 'Amethyst',
    planet: 'Saturn (Uranus influence)',
    benefits: [
      'Enhances intuition and spiritual awareness',
      'Promotes mental clarity and sobriety',
      'Supports innovative thinking',
      'Calms anxiety and stress',
    ],
    wearingMethod: 'Set in silver on the middle finger. Meditate with the stone before wearing.',
    recommendedMetal: 'Silver',
    recommendedFinger: 'Middle finger (right hand)',
    recommendedDay: 'Saturday',
    zodiacSigns: ['Aquarius'],
  },
];

/** Zodiac to primary gemstone mapping per business rules */
export const ZODIAC_GEMSTONE_MAP: Record<ZodiacSign, string> = {
  Aries: 'Ruby',
  Taurus: 'Emerald',
  Gemini: 'Emerald',
  Cancer: 'Pearl',
  Leo: 'Ruby',
  Virgo: 'Emerald',
  Libra: 'Diamond',
  Scorpio: 'Coral',
  Sagittarius: 'Yellow Sapphire',
  Capricorn: 'Blue Sapphire',
  Aquarius: 'Amethyst',
  Pisces: 'Yellow Sapphire',
};
